name: example_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  zoom_tap_animation: ^1.1.0
  flutter_screenutil: ^5.8.4
  percent_indicator: ^4.2.3
  change_app_package_name: ^1.1.0
  easy_localization: ^3.0.2
  cached_network_image: ^3.3.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  another_transformer_page_view: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/

  fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
      - asset: assets/fonts/OpenSans-Bold.ttf